spring.application.name=ollamademo

# Ollama Configuration
spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.options.model=qwen3:4b-q4_K_M
spring.ai.ollama.chat.options.model=llama3.2
spring.ai.ollama.embedding.enabled=true
spring.ai.ollama.embedding.options.model=qwen3-embedding:0.6b

# Perplexity Configuration
spring.ai.openai.api-key=${PERPLEXITY_API_KEY}
spring.ai.openai.base-url=https://api.perplexity.ai
spring.ai.openai.chat.completions-path=/chat/completions
spring.ai.openai.chat.options.model=sonar
spring.ai.openai.chat.options.temperature=0.7

spring.datasource.url=jdbc:h2:file:~/chatmemory;AUTO_SERVER=true
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=vijay
spring.datasource.password=12345
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
#spring.ai.openai.embedding.options.model=text-embedding-3-small

spring.ai.chat.memory.repository.jdbc.initialize-schema=always
spring.ai.chat.memory.repository.jdbc.schema=classpath:/schema/schema-h2db.sql

spring.docker.compose.enabled=false
spring.docker.compose.stop.command=down

spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=vijayv1

server.port=8091
